# Deep Learning Practice with Python

### Vectorization

In [ ]:
import numpy as np
import time

a = np.random.rand(1000000)
c = np.random.rand(1000000)

tic = time.time()
j = np.dot(a, c)
toc = time.time()
print(j)
print(f"vectorization time required {toc - tic} ms")

In [ ]:
tic = time.time()
j = 0
for i in range(1000000):
  j += a[i] * c[i]

toc = time.time()
print(j)
print(f"Loop time required {toc - tic} ms")


### Eliminating explicit `for` loops
We can use numpy to eleminate explicit for loop. This is called vectorization.
For example,
```py
    import numpy as np
    a = np.array([1, 2, 3, 4])
    b = np.zeros(4)
    for i in range(len(a)):
        b[i] = exp(a[i])
```
Instead of using the for loop in the above code, we can use vectorization as follows:
```py
    b = np.exp(a)
```

In [11]:
b = np.random.rand(10)
d = np.random.rand(10)

print(b)
print(d)

result = np.matmul(b.T, d)
print(result)

[0.99708094 0.77200488 0.28916807 0.02761593 0.19655654 0.98568535
 0.81325183 0.47251332 0.61582071 0.98130091]
[0.37144922 0.98305349 0.51313961 0.12477931 0.65214988 0.35260995
 0.36853514 0.85482349 0.04781707 0.51059492]
2.990984676148329


### Broadcasting
In this example, we want to compute the percentage of calories for Cub, Protein, Fat (rows) in Apples, Beef, Eggs, Potatoes (columns) without using explicit for loops.

In [13]:
A = np.array([
    [56.0, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]
])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [14]:
# Summing column wise to find total calories of each food item
cal = A.sum(axis = 0) 
print(cal)

[ 59.  239.  155.4  76.9]


In [15]:
percentage = 100 * A/cal.reshape(1, 4) # reshape transforms row matrix to column
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


### A note on Python/Numpy vectors
Generally, while adding a row vector with a column vector, we need to transpose the row vector. However, in Python/Numpy, we can add a row vector with a column vector without transposing the row vector. This might create unexpected results if we are not careful. Here are some tricks to minimize these logical errors:

In [16]:
a = np.random.randn(5)
print(a)

[ 1.25983996  0.20994328 -0.39356585  1.41032523  1.3587906 ]


In [17]:
print(a.shape)

(5,)


In [18]:
print(a.T)

[ 1.25983996  0.20994328 -0.39356585  1.41032523  1.3587906 ]


In [19]:
print(np.dot(a, a.T))

5.6214961233403455


In the above example, `a` and `a.T` looks the same. And the dot product outputs a number. This is because we have used `np.random.randn(5)`. Because it creates a datastructure of `a.shape = (5,)`. But if we use `np.random.randn(5, 1)`, then it will create a datastructure of `a.shape = (5,1)`. And the dot product will output a vector.

In [20]:
a = np.random.randn(5, 1)
print(a)

[[ 0.19017918]
 [-0.58789109]
 [-0.51846927]
 [-0.20603012]
 [-1.5858999 ]]


In [21]:
print(a.T)

[[ 0.19017918 -0.58789109 -0.51846927 -0.20603012 -1.5858999 ]]


In [22]:
print(np.dot(a, a.T))

[[ 0.03616812 -0.11180464 -0.09860206 -0.03918264 -0.30160514]
 [-0.11180464  0.34561593  0.30480346  0.12112327  0.93233642]
 [-0.09860206  0.30480346  0.26881038  0.10682029  0.82224036]
 [-0.03918264  0.12112327  0.10682029  0.04244841  0.32674315]
 [-0.30160514  0.93233642  0.82224036  0.32674315  2.51507849]]
